package net.dohaw.play.divisions.rank;

public enum RankPermission {

    CAN_TAKE_FROM_BANK,
    CAN_KICK_PLAYERS,
    CAN_RECRUIT_MEMBERS,
    CAN_SEND_DIVISION_ANNOUNCEMENTS,
    CAN_INVITE_PLAYERS,
    CAN_DECLARE_WAR,
    CAN_STOP_WAR,
    CAN_ALLY,
    CAN_DISCONTINUE_ALLY,
    CAN_ALTER_STATUS,
    CAN_PROMOTE_MEMBERS,
    CAN_DEMOTE_MEMBERS,
    CAN_UPGRADE_STRUCTURES,
    CAN_COLLECTION_FROM_MINER,
    CAN_COLLECT_FROM_WOODCUTTER,
    CAN_PURCHASE_STRUCTURES,
    CAN_ACCESS_WORTHY_CHAT,
    CAN_ACCEPT_DIVISION_QUESTS,
    CAN_ABANDON_DIVISION_QUESTIONS,
    CAN_SET_DIVISION_MOTD,
    CAN_HIRE_WORKERS,
    ITEM_TAKE_AMOUNT,
    GOLD_TAKE_AMOUNT;

}
