Plugin Prefix: "&l[&aDivisions&r&l]&r"

Debug Mode: true
No CoolDown Mode: true
Default Division Gold Amount: 100
Invite Cooldown: 5

Base Regeneration Interval: 20
Base Regeneration Amount: 10
Base Regeneration Max: 100
Percentage Reduction Per Restoration Point: 0.03
Mininmum Regeneration Percentage: 0.05

Calculations:

  Scale:
    Melee Damage Scale: 1.35
    Toughness Scale: 1.2
    Bow Damage Scale: 1.2
    Spell Power Damage Scale: 1.35

  Division Scale:
    Melee Damage Division Scale: 1.35
    Ranged Damage Division Scale: 1.35
    Spell Power Damage Division Scale: 1.35
    Raw Stat Division Scale: 60
    Raw Stat Division Totality Scale: 1.665


  Spells:
    Heating Up:
      Total Luck Multiple: 2
    Escape:
      Velocity Scale: 2
    Leap:
      Base Damage: 2
      Heart Increase Per Strength: 1
      Strength Interval: 5
      Y Level Increase: 1
      Velocity Scale: 2
      Radius: 3
      Damage Scale: 1
    Photosynthesis:
      Interval: 30
