name: Divisions
version: ${project.version}
main: net.dohaw.play.divisions.DivisionsPlugin
api-version: 1.13

commands:
  divisions:
    description: "Base command for this plugin"
    aliases:
      - div
      - division
  divisionsconfirm:
    description: "For confirmable commands"
