name: Divisions
version: ${project.version}
main: net.dohaw.play.divisions.DivisionsPlugin
api-version: 1.13
depend:
  - CoreAPI
  - Vault
commands:

  divisions:
    description: "Base command for this plugin"
    aliases:
      - div
      - division
  divisionsconfirm:
    description: "For confirmable commands"
  archetypes:
    description: "Command to deal with Archetype things"
    aliases:
      - ar
      - arch
      - arc
  customitems:
    description: "Brings up menus for creating custom items"
    aliases:
      - cui
      - customi
      - citems
      - citem
      - customitem
      - ci
